### ISSUE TITLE
Unable to locate Icon.ico

### ISSUE THREAD

**Issue by johnosbb** [runesc/PPG#3]
Hi,

I created a new project with ppg init
I then ran ppg start
I get the error 
FileNotFoundError: [Errno 2] Could not locate resource: 'Icon.ico'

**Comment by johnosbb** [comment]
It is looking for Icon.ico, this should be icon.ico

**Comment by runesc** [comment]
Hi,

Thank you for reporting the issue. We have resolved the problem with the 'Icon.ico' file, which should actually be 'icon.ico'. The fix will be included in the next update, which will be released in a few weeks, along with the first official documentation.

Thank you for your patience and support!
